FROM docker-asr-release.dr.corp.adobe.com/asr/nodejs-v6:1.0-alpine

COPY package.json package.json
COPY .npmrc .npmrc

RUN npm install

COPY . .

RUN npm run build

ARG PATH_PREFIX=""

RUN deploy-scripts/pre-process-dist.sh

CMD ["tar", "-c", "build-artifacts", "dist", "Dockerfile.s3", "Dockerfile.nginx", "deploy-scripts"]
