FROM docker-asr-release.dr.corp.adobe.com/asr/nodejs-v7:1.0

RUN apt-get update && apt-get install -y bzip2 git libfontconfig1

COPY package.json package.json
COPY .npmrc .npmrc

RUN npm install

COPY . .

RUN npm run build

RUN npm run test

ARG PATH_PREFIX=""

RUN deploy-scripts/pre-process-dist.sh

CMD ["tar", "-c", "build-artifacts", "dist", "Dockerfile.s3", "Dockerfile.nginx", "deploy-scripts"]
